const en = {
  name: 'Name',
  login: 'Login',
  finish: 'Finish',
  chooseALogin: 'choose a login',
  next: 'Next',
  whatsYourName: 'Whats your name ?',
  enterAPassword: 'Enter a password',
  passwordChoiceRule: 'Choose a password that contains at least 5 characters',
  password: 'Password',
  enter: 'Enter',
  home: 'Home',
  brand: 'Brand',
  productType: 'Product type',
  productTypes: 'Product types',
  product: 'Product',
  products: 'Products',
  purchaseList: 'Purchase list',
  purchases: 'Purchases',
  createAccount: 'Create account',
  brands: 'Brands',
  logout: 'Log out',
  cancel: 'Cancel',
  clearFilters: 'Clear filters',
  filter: 'Filter',
  createAccountConfirmationMessage: 'Confirm your data to complete the registration',
  description: 'Description',
  save: 'Save',
  delete: 'Delete',
  id: 'Id',
  ok: 'OK',
  fieldRequiredErrorDefault: 'This field is required',
  genericDeleteConfirmationTitle: 'Delete',
  genericDeleteConfirmationMessage: 'Do you want to confirm ?',
  noDataFoundMessage: 'No data found',
  items: 'items',

  deleteBrandConfirmationTitle: 'Delete brand',
  deleteBrandConfirmationMessage: 'Do you want to confirm the brand {{brandName}} removal ?',
  noBrandFound: 'No brand found',
  brandMissingNameFieldError: 'The brand name is required',

  deleteProductTypeConfirmationTitle: 'Delete productType',
  deleteProductTypeConfirmationMessage: 'Do you want to confirm the product type {{productTypeName}} removal ?',
  noProductTypeFound: 'No product type found',
  productTypeMissingNameFieldError: 'The productType name is required',
  parentProductType: 'Parent product type',

  deleteProductConfirmationTitle: 'Delete product',
  deleteProductConfirmationMessage: 'Do you want to confirm the product type {{productName}} removal ?',
  noProductFound: 'No product type found',
  productMissingNameFieldError: 'The product name is required',

  deletePurchaseListConfirmationTitle: 'Delete purchase list',
  deletePurchaseListConfirmationMessage: 'Do you want to confirm the purchase list type {{purchaseListName}} removal ?',
  noPurchaseListFound: 'No purchase list found',
  purchaseListMissingNameFieldError: 'The purchase list name is required',

  // errors

  genericErrorTitle: 'Something is wrong',
  genericErrorMessage: 'We were unable to perform this action. Take a look if you have internet access. For this feature it is necessary to be connected to the internet.',
  userRegisterErrorTitle: 'Error during registration',
  loginAlreadyExistsErrorMessage: 'The login \'{{login}}\' already exists. Please choose another one and try again',
  invalidCredentialsTitle: 'Invalid credentials',
  invalidCredentialsMessage: 'Login or password are not correct',
  genericServerErrorTitle: 'Error',
  genericServerErrorMessage: 'An internal error occurred. Ask for help.',
};

export default en;
