const ptBR = {
  name: 'Nome',
  login: 'Login',
  finish: 'Finalizar',
  chooseALogin: 'escolha um login',
  next: 'Próximo',
  whatsYourName: 'Qual seu nome ?',
  enterAPassword: 'Insira uma senha',
  passwordChoiceRule: 'Escolha uma senha que contenha ao menos 5 caracteres',
  password: 'Senha',
  enter: 'Entrar',
  home: 'Início',
  brand: 'Marca',
  productType: 'Tipo de produto',
  productTypes: 'Tipos de produto',
  product: 'Produto',
  products: 'Produtos',
  purchaseList: 'Lista de compra',
  purchases: 'Compras',
  createAccount: 'Criar conta',
  brands: 'Marcas',
  logout: 'Sair',
  cancel: 'Cancelar',
  clearFilters: 'Limpar filtros',
  filter: 'Filtrar',
  createAccountConfirmationMessage: 'Confirme seus dados para finalizar o cadastro',
  description: 'Descrição',
  save: 'Salvar',
  delete: 'Deletar',
  id: 'Id',
  ok: 'OK',
  fieldRequiredErrorDefault: 'Este campo é obrigatório',
  genericDeleteConfirmationTitle: 'Delete',
  genericDeleteConfirmationMessage: 'Do you want to confirm ?',
  noDataFoundMessage: 'Nenhum dado encontrado',
  items: 'itens',
  remove: 'Remover',

  deleteBrandConfirmationTitle: 'Deletar marca',
  deleteBrandConfirmationMessage: 'Deseja confirma a deleção da marca {{brandName}} ?',
  noBrandFound: 'Nenhuma marca cadastrada',
  brandMissingNameFieldError: 'O nome da marca é obrigatório',

  deleteProductTypeConfirmationTitle: 'Deletar tipo de produto',
  deleteProductTypeConfirmationMessage: 'Deseja confirma a deleção do tipo de produto {{productTypeName}} ?',
  noProductTypeFound: 'Nenhum tipo de produto cadastrado',
  productTypeMissingNameFieldError: 'O nome do tipo de produto é obrigatório',
  parentProductType: 'Tipo de produto pai',

  deleteProductConfirmationTitle: 'Deletar produto',
  deleteProductConfirmationMessage: 'Deseja confirma a deleção do produto {{productName}} ?',
  noProductFound: 'Nenhum produto cadastrado',
  productMissingNameFieldError: 'O nome do produto é obrigatório',

  deletePurhcaseListConfirmationTitle: 'Deletar lista de compra',
  deletePurhcaseListConfirmationMessage: 'Deseja confirma a deleção do lista de compra {{purchaseListName}} ?',
  noPurhcaseListFound: 'Nenhum lista de compra cadastrada',
  purchaseListMissingNameFieldError: 'O nome da lista de compra é obrigatório',

  // errors

  genericErrorTitle: 'Algo de errado não está certo',
  genericErrorMessage: 'Não conseguimos efetuar essa ação. Dá uma olhada se está com acesso a internet. Para esse recurso é necessário estar conectado a internet.',
  userRegisterErrorTitle: 'Erro durante o cadastro',
  loginAlreadyExistsErrorMessage: 'O login {{login}} já existe. Por favor escolha outro e tente novamente',
  invalidCredentialsTitle: 'Credenciais inválidas',
  invalidCredentialsMessage: 'Usuário ou senha incorretos',
  genericServerErrorTitle: 'Erro',
  genericServerErrorMessage: 'Ocorreu um erro interno daqueles que ninguém achou que poderia acontecer. Peça ajuda.',
};

export default ptBR;
